# Generated by Django 2.2 on 2020-01-19 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindergarten', models.CharField(choices=[('Kita-Fröbel', 'Kita-Fröbel'), ('Kita-Abenteuerwelt', 'Kita-Abenteuerwelt'), ('Kita-Rübchen', 'Kita-Rübchen')], max_length=50)),
                ('user_type', models.CharField(choices=[('PA', 'Eltern'), ('ED', 'Erzieher'), ('GL', 'Gruppenleiter'), ('KM', 'Kitaleitung'), ('A', 'Admin')], default='Eltern', max_length=50)),
                ('is_aproved', models.BooleanField(default=False)),
                ('mitgliedsnummer', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
