# Generated by Django 2.2 on 2020-01-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date_published'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
