# Generated by Django 2.2 on 2020-01-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200121_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_published'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
