# Generated by Django 2.2 on 2020-01-21 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200121_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
