# Generated by Django 2.2 on 2020-01-19 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppenname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
                'ordering': ['gruppenname'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
                ('zeitpunkt_des_beitritts', models.DateTimeField(auto_now_add=True)),
                ('elternteil_1', models.CharField(max_length=50)),
                ('elternteil_2', models.CharField(max_length=50)),
                ('mitgliedsnummer', models.CharField(max_length=10)),
                ('eltern_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', related_query_name='user', to=settings.AUTH_USER_MODEL)),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinderübersicht.Gruppe')),
            ],
            options={
                'verbose_name': 'Kind',
                'verbose_name_plural': 'Kinder',
                'ordering': ['vorname'],
            },
        ),
        migrations.CreateModel(
            name='Mitteilung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('erstellungs_datum', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinderübersicht.Kind')),
            ],
            options={
                'verbose_name': 'Mitteilung',
                'verbose_name_plural': 'Mitteilungen',
                'ordering': ['erstellungs_datum'],
            },
        ),
        migrations.CreateModel(
            name='Entwicklernotiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('erstellungs_datum', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('SP', 'Sprache'), ('SOV', 'Sozialverhalten'), ('KO', 'Kognition'), ('FM', 'Feinmotorik'), ('GM', 'Grobmotorik'), ('KuP', 'Körper und Pflegebewusstsein'), ('SPV', 'Spielverhalten'), ('UB', 'Umgebungsbewusstsein')], max_length=3)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinderübersicht.Kind')),
            ],
            options={
                'verbose_name': 'Entwicklernotiz',
                'verbose_name_plural': 'Entwicklernotizen',
                'ordering': ['erstellungs_datum'],
            },
        ),
    ]
