# Generated by Django 2.2 on 2020-01-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinderübersicht', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entwicklernotiz',
            options={'ordering': ['-erstellungs_datum'], 'verbose_name': 'Entwicklernotiz', 'verbose_name_plural': 'Entwicklernotizen'},
        ),
    ]
